In [2]:
import pandas as pd

In [3]:
excel_name = 'table3B_satellite_v3-1.csv'
df3 = pd.read_csv(excel_name)

In [4]:
df3.head(14)

,Sys,Band,Signal,Frequency[MHz],Modulation,Rate(MHz),P_t (dBW),G_t (dBi),Alpha
0,GPS,L1,P(Y),1575.42,BPSK(10),10.2300,13.5,13.5,1.5
1,GPS,L1,C/A,1575.42,BPSK(1),1.0230,16.5,13.5,1.5
2,GPS,L1,L1C-D,1575.42,"TMBOC(6,1,4/33)",1.0230,10.0,10.0,1.5
3,GPS,L1,L1C-P,1575.42,"TMBOC(6,1,4/33)",1.0230,10.0,10.0,1.5
4,GPS,L1,M-D,1575.42,"BOC(10,5)",5.1150,18.2,13.5,1.5
5,GPS,L1,M-P,1575.42,"BOC(10,5)",5.1150,18.2,13.5,1.5
6,GPS,L2,P(Y),1227.60,BPSK(10),10.2300,10.0,10.0,1.5
7,GPS,L2,L2CM,1227.60,BPSK(1),0.5115,10.0,10.0,1.5
8,GPS,L2,L2CL,1227.60,BPSK(1),0.5115,10.0,10.0,1.5
9,GPS,L2,M-D,1227.60,"BOC(10,5)",5.1150,16.0,13.5,1.5
10,GPS,L2,M-P,1227.60,"BOC(10,5)",5.1150,16.0,13.5,1.5
11,GPS,L5,L5I,1176.45,BPSK(10),10.2300,18.0,18.0,1.0
12,GPS,L5,L5Q,1176.45,BPSK(10),10.2300,18.0,18.0,1.0
13,GLO,L1,L1SF(P),1602.00,BPSK(5),5.1100,0.0,0.0,0.6

In [76]:
# Incase you need to remove indexes {nan only}

# df3 = df3.drop(71)

In [77]:
fs, fe = 1220, 1240

# data_n = df3[df3['Frequency[MHz]'] < fe]
# data_n = data_n[data_n['Frequency[MHz]'] > fs]
# data_n.sort_values(by='Frequency[MHz]', ascending=True)
# data_n

In [78]:
# # Searching for satellite by name

# sat = 'SBAS'

# sat_type = df3[df3['Sys'].str.contains(sat)]
# sat_type
# # sat_type.sort_values(by='Index', ascending=True)

In [84]:
# Index for which satellite to obtain

# idx = [7,8]
# idx = [20]

idx = [x for x in range(11, 13, 1)]

In [85]:
idx

[11, 12]

In [86]:
# # Power or gain
x = 1


for i in idx:
    df3.loc[i, 'Alpha'] = x




# # Change the frequency values

# for i in idx:
#     df3.loc[i, 'Frequency[MHz]'] = 1248.3

In [87]:
# df3[df3['Sys'].str.contains(sat)]

# data_n = df3[df3['Frequency[MHz]'] < fe]
# data_n = data_n[data_n['Frequency[MHz]'] > fs]
# data_n.sort_values(by='Frequency[MHz]', ascending=True)

In [88]:
df3.to_csv(path_or_buf=excel_name, index=None)

In [89]:
df3.head(15)

,Sys,Band,Signal,Frequency[MHz],Modulation,Rate(MHz),P_t (dBW),G_t (dBi),Alpha
0,GPS,L1,P(Y),1575.42,BPSK(10),10.2300,13.5,13.5,1.5
1,GPS,L1,C/A,1575.42,BPSK(1),1.0230,16.5,13.5,1.5
2,GPS,L1,L1C-D,1575.42,"TMBOC(6,1,4/33)",1.0230,10.0,10.0,1.5
3,GPS,L1,L1C-P,1575.42,"TMBOC(6,1,4/33)",1.0230,10.0,10.0,1.5
4,GPS,L1,M-D,1575.42,"BOC(10,5)",5.1150,18.2,13.5,1.5
5,GPS,L1,M-P,1575.42,"BOC(10,5)",5.1150,18.2,13.5,1.5
6,GPS,L2,P(Y),1227.60,BPSK(10),10.2300,10.0,10.0,1.5
7,GPS,L2,L2CM,1227.60,BPSK(1),0.5115,10.0,10.0,1.5
8,GPS,L2,L2CL,1227.60,BPSK(1),0.5115,10.0,10.0,1.5
9,GPS,L2,M-D,1227.60,"BOC(10,5)",5.1150,16.0,13.5,1.5
10,GPS,L2,M-P,1227.60,"BOC(10,5)",5.1150,16.0,13.5,1.5
11,GPS,L5,L5I,1176.45,BPSK(10),10.2300,18.0,18.0,1.0
12,GPS,L5,L5Q,1176.45,BPSK(10),10.2300,18.0,18.0,1.0
13,GLO,L1,L1SF(P),1602.00,BPSK(5),5.1100,0.0,0.0,0.6
14,GLO,L1,L1OF(C/A),1602.00,BPSK(0.5),0.5110,0.0,0.0,0.6

### ------------------------------ END -----------------------------------------

In [40]:
# print df3.sort_values(by='Frequency[MHz]', ascending=True).to_latex(index=False)

# # print df3.to_latex(index=False)

In [ ]:
import pickle
import numpy as np

Going to make a panda data frame for the csv file

In [ ]:
df = df3.rename(columns={'P_txG_t(dB)': 'Alpha'})

In [ ]:
df.shape[0]

In [ ]:
idx = np.arange(df.shape[0])
for i in idx:
    df.loc[i, 'Alpha'] = 1

In [ ]:
df.to_pickle('table3B_satellite_v3.p')

In [ ]:
pickle.load(open('table3B_satellite_v3.p', 'rb'), encoding='latin1')