In [1]:
import pandas as pd

In [15]:
excel_name = 'table3B_satellite_v3.csv'
df3 = pd.read_csv(excel_name)

In [3]:
# Incase you need to remove indexes {nan only}

# df3 = df3.drop(76)

In [4]:
# df3.sort_values(by='Frequency[MHz]', ascending=True)

In [62]:
fs, fe = 1220, 1240

In [63]:
data_n = df3[df3['Frequency[MHz]'] < fe]
data_n = data_n[data_n['Frequency[MHz]'] > fs]
data_n.sort_values(by='Frequency[MHz]', ascending=True)
data_n

,Sys,Band,Signal,Frequency[MHz],Modulation,Rate(MHz),P_t (dBW),G_t (dBi),P_txG_t(dB)
6,GPS,L2,P(Y),1227.6,BPSK(10),10.2300,10.0,10.0,20.0
7,GPS,L2,L2CM,1227.6,BPSK(1),0.5115,10.0,10.0,20.0
8,GPS,L2,L2CL,1227.6,BPSK(1),0.5115,10.0,10.0,20.0
9,GPS,L2,M-D,1227.6,"BOC(10,5)",5.1150,16.0,13.5,29.5
10,GPS,L2,M-P,1227.6,"BOC(10,5)",5.1150,16.0,13.5,29.5
57,QZS-1,L2,L2CM,1227.6,BPSK(1),0.5115,0.0,0.0,0.0
58,QZS-1,L2,L2CL,1227.6,BPSK(1),0.5115,0.0,0.0,0.0

In [7]:
# # Searching for satellite by name

# sat = 'SBAS'

# sat_type = df3[df3['Sys'].str.contains(sat)]
# sat_type
# # sat_type.sort_values(by='Index', ascending=True)

In [58]:
# Index for which satellite to obtain

idx = [7,8]
# idx = [20]

# idx = [x for x in range(0, 77, 1)]

In [59]:
# # Power or gain
x1, x2 = 10, 10


for i in idx:
    df3.loc[i, 'P_t (dBW)'] = x1
    df3.loc[i, 'G_t (dBi)'] = x2
    df3.loc[i, 'P_txG_t(dB)'] = x1+x2



# # Change the frequency values

# for i in idx:
#     df3.loc[i, 'Frequency[MHz]'] = 1248.3

In [60]:
# df3[df3['Sys'].str.contains(sat)]

data_n = df3[df3['Frequency[MHz]'] < fe]
data_n = data_n[data_n['Frequency[MHz]'] > fs]
data_n.sort_values(by='Frequency[MHz]', ascending=True)

,Sys,Band,Signal,Frequency[MHz],Modulation,Rate(MHz),P_t (dBW),G_t (dBi),P_txG_t(dB)
6,GPS,L2,P(Y),1227.6,BPSK(10),10.2300,10.0,10.0,20.0
7,GPS,L2,L2CM,1227.6,BPSK(1),0.5115,10.0,10.0,20.0
8,GPS,L2,L2CL,1227.6,BPSK(1),0.5115,10.0,10.0,20.0
9,GPS,L2,M-D,1227.6,"BOC(10,5)",5.1150,16.0,13.5,29.5
10,GPS,L2,M-P,1227.6,"BOC(10,5)",5.1150,16.0,13.5,29.5
57,QZS-1,L2,L2CM,1227.6,BPSK(1),0.5115,0.0,0.0,0.0
58,QZS-1,L2,L2CL,1227.6,BPSK(1),0.5115,0.0,0.0,0.0

In [61]:
df3.to_csv(path_or_buf=excel_name, index=None)

### ------------------------------ END -----------------------------------------

In [ ]:
# print df3.sort_values(by='Frequency[MHz]', ascending=True).to_latex(index=False)

# # print df3.to_latex(index=False)