In [1]:
import pandas as pd
import numpy as np

In [2]:

df_2bw = pd.read_csv('table3B_satellite_v3-1_reduced_2_bw.csv') 
# df_2shuffle = pd.read_csv('table3B_satellite_v3-1_reduced_2.csv')

In [12]:
# for i in [12, 13, 21,22,25,26]:
#     df3 = df3.drop(index=i)


df_2bw = df_2bw.reset_index(drop=True)
for i in [4, 5]:
    df_2bw.loc[i, 'P_t (dBW)'] = 10
    df_2bw.loc[i, 'G_t (dBi)'] = 10


# Changing specific values per row and column value
# df3.loc[:, 'Alpha'] = 1


## Changing specific values per column
# df3.loc[df3['P_t (dBW)'] < 10.5, 'P_t (dBW)'] = 13.5
# df3.loc[df3['G_t (dBi)'] < 10.5, 'G_t (dBi)'] = 13.5
# df3.loc[df3['Alpha'] < 2, 'Alpha'] = 1


## Selecting specific frequency slices and removing specific system values
# fs, fe = 1150, 1305
# data_n = df3[df3['Frequency[MHz]'] < fe]
# data_n = data_n[data_n['Frequency[MHz]'] > fs]
# data_n = data_n[data_n['Sys'].str.contains('QZS-1')==False]
# data_n = data_n.sort_values(by='Frequency[MHz]', ascending=True)

In [13]:
# for i in [12, 13, 21,22,25,26]:
#     df3 = df3.drop(index=i)

In [14]:
df_2bw

,Sys,Band,Signal,Frequency[MHz],Bandwidth,Modulation,Rate(MHz),P_t (dBW),G_t (dBi),Alpha,Sigma
0,GPS,L1,P(Y),1575.420,10.0,BPSK(10),10.2300,13.5,13.5,1,1
1,GPS,L1,C/A,1575.420,1.0,BPSK(1),1.0230,16.5,13.5,1,1
2,GPS,L1,L1C-D,1575.420,2.0,"TMBOC(6,1,4/33)",1.0230,10.0,10.0,1,1
3,GPS,L1,M-D,1575.420,15.0,"BOC(10,5)",5.1150,18.2,13.5,1,1
4,GPS,L2,P(Y),1227.600,10.0,BPSK(10),10.2300,10.0,10.0,1,1
5,GPS,L2,L2CM,1227.600,1.0,BPSK(1),0.5115,10.0,10.0,1,1
6,GPS,L2,M-D,1227.600,15.0,"BOC(10,5)",5.1150,16.0,13.5,1,1
7,GPS,L5,L5I,1176.450,10.0,BPSK(10),10.2300,18.0,18.0,1,1
8,GLO,L1,L1SF(P),1602.000,5.0,BPSK(5),5.1100,10.0,10.0,1,1
9,GLO,L2,L2SF(P),1245.100,5.0,BPSK(5),5.1100,10.0,10.0,1,1
10,GLO,L2,L2OF(C/A),1245.100,0.5,BPSK(0.5),0.5110,10.0,10.0,1,1
11,GLO,L3,L3OC-D,1202.025,10.0,BPSK(10),10.2300,10.0,10.0,1,1
12,GLO,L2,L2OC-D,1248.300,1.0,BPSK(1),1.0230,13.0,12.0,1,1
13,GLO,L2,L2OC-P,1248.300,2.0,"BOC(1,1)",0.5115,5.0,5.0,1,1
14,GAL,E1,OS-D(B),1575.420,2.0,"CBOC(6,1,1/11)",1.0230,10.0,10.0,1,1
15,GAL,E6,CS-P(C),1278.750,5.0,BPSK(5),5.1150,16.0,15.0,1,1
16,GAL,E6,PRS(A),1278.750,15.0,"BOCcos(10,5)",5.1150,18.0,16.0,1,1
17,GAL,E5ab,PRS(A),1191.795,25.0,"AltBOC(15,10)",10.2300,10.0,10.0,1,1
18,GAL,E5a,E5a-D,1176.450,10.0,"AltBOC(15,10)",10.2300,6.0,6.0,1,1
19,BDS-2,B1-2,RS,1561.098,2.0,BPSK(2),2.0460,10.0,10.0,1,1
20,BDS-2,B3,RS,1268.520,10.0,BPSK(10),10.2300,16.0,16.0,1,1
21,BDS-2,B2b,OS,1207.140,2.0,BPSK(2),2.0460,14.0,12.0,1,1
22,BDS-2,B2b,RS,1207.140,10.0,BPSK(10),10.2300,18.0,18.0,1,1
23,BDS-3,B1-2,OS,1561.098,2.0,BPSK(2),2.0460,10.0,10.0,1,1
24,BDS-3,B1,B1C-Dl,1575.420,2.0,"TMBOC(6,1,4/33)",1.0230,10.0,10.0,1,1
25,BDS-3,B3,B3C-Dm,1268.520,10.0,BPSK(10),10.2300,15.0,13.5,1,1
26,BDS-3,B3,B3A-Dm,1268.520,10.0,"BOC(15,2.5)",2.5575,10.0,10.0,1,1
27,QZS-1,L1,C/A,1575.420,1.0,BPSK(1),1.0230,10.0,10.0,1,1
28,QZS-1,L1,L1C-D,1575.420,2.0,"BOC(1,1)",1.0230,10.0,10.0,1,1
29,QZS-1,L1,L1C-D,1575.420,2.0,"TMBOC(6,1,4/33)",1.0230,10.0,10.0,1,1
30,QZS-1,L1,SAIF,1575.420,1.0,BPSK(1),1.0230,10.0,10.0,1,1
31,QZS-1,L2,L2CL,1227.600,1.0,BPSK(1),0.5115,10.0,10.0,1,1
32,QZS-1,L6,L61(LEX)n,1278.750,5.0,BPSK(5),5.1150,10.0,10.0,1,1
33,QZS-1,L6,L62o,1278.750,5.0,BPSK(5),5.1150,10.0,10.0,1,1
34,QZS-1,L5,L5I,1176.450,10.0,BPSK(10),10.2300,16.0,16.0,1,1
35,QZS-1,L5,L5Q,1176.450,10.0,BPSK(10),10.2300,16.0,16.0,1,1
36,IRNSS,L5,SPS,1176.450,24.0,BPSK(1),1.0230,16.0,14.0,1,1
37,IRNSS,L5,RS-D,1176.450,16.0,"BOC(5,2)",2.0460,18.0,16.0,1,1
38,SBAS,L1,C/A,1575.420,1.0,BPSK(1),1.0230,13.0,13.5,1,1
39,SBAS,L5,L5I,1176.450,10.0,BPSK(10),10.2300,18.0,16.0,1,1

In [4]:
# peidf_2bw.to_latex(index=False)

In [16]:
10**np.log10(11.46)*10**np.log10(11.46)

131.33160000000007

In [14]:
np.log10(14)*10

11.46128035678238

In [5]:
df_2bw.loc[(df_2bw['Frequency[MHz]'] >= 1150) & (df_2bw['Frequency[MHz]'] <= 1350)]

,Sys,Band,Signal,Frequency[MHz],Bandwidth,Modulation,Rate(MHz),P_t (dBW),G_t (dBi),Alpha,Sigma
4,GPS,L2,P(Y),1227.600,10.0,BPSK(10),10.2300,10.0,10.0,1,1
5,GPS,L2,L2CM,1227.600,1.0,BPSK(1),0.5115,10.0,10.0,1,1
6,GPS,L2,M-D,1227.600,15.0,"BOC(10,5)",5.1150,16.0,13.5,1,1
7,GPS,L5,L5I,1176.450,10.0,BPSK(10),10.2300,18.0,18.0,1,1
9,GLO,L2,L2SF(P),1245.100,5.0,BPSK(5),5.1100,10.0,10.0,1,1
10,GLO,L2,L2OF(C/A),1245.100,0.5,BPSK(0.5),0.5110,10.0,10.0,1,1
11,GLO,L3,L3OC-D,1202.025,10.0,BPSK(10),10.2300,10.0,10.0,1,1
12,GLO,L2,L2OC-D,1248.300,1.0,BPSK(1),1.0230,13.0,12.0,1,1
13,GLO,L2,L2OC-P,1248.300,2.0,"BOC(1,1)",0.5115,5.0,5.0,1,1
15,GAL,E6,CS-P(C),1278.750,5.0,BPSK(5),5.1150,16.0,15.0,1,1
16,GAL,E6,PRS(A),1278.750,15.0,"BOCcos(10,5)",5.1150,18.0,16.0,1,1
17,GAL,E5ab,PRS(A),1191.795,25.0,"AltBOC(15,10)",10.2300,10.0,10.0,1,1
18,GAL,E5a,E5a-D,1176.450,10.0,"AltBOC(15,10)",10.2300,6.0,6.0,1,1
20,BDS-2,B3,RS,1268.520,10.0,BPSK(10),10.2300,16.0,16.0,1,1
21,BDS-2,B2b,OS,1207.140,2.0,BPSK(2),2.0460,14.0,12.0,1,1
22,BDS-2,B2b,RS,1207.140,10.0,BPSK(10),10.2300,18.0,18.0,1,1
25,BDS-3,B3,B3C-Dm,1268.520,10.0,BPSK(10),10.2300,15.0,13.5,1,1
26,BDS-3,B3,B3A-Dm,1268.520,10.0,"BOC(15,2.5)",2.5575,10.0,10.0,1,1
31,QZS-1,L2,L2CL,1227.600,1.0,BPSK(1),0.5115,10.0,10.0,1,1
32,QZS-1,L6,L61(LEX)n,1278.750,5.0,BPSK(5),5.1150,10.0,10.0,1,1
33,QZS-1,L6,L62o,1278.750,5.0,BPSK(5),5.1150,10.0,10.0,1,1
34,QZS-1,L5,L5I,1176.450,10.0,BPSK(10),10.2300,16.0,16.0,1,1
35,QZS-1,L5,L5Q,1176.450,10.0,BPSK(10),10.2300,16.0,16.0,1,1
36,IRNSS,L5,SPS,1176.450,24.0,BPSK(1),1.0230,16.0,14.0,1,1
37,IRNSS,L5,RS-D,1176.450,16.0,"BOC(5,2)",2.0460,18.0,16.0,1,1
39,SBAS,L5,L5I,1176.450,10.0,BPSK(10),10.2300,18.0,16.0,1,1

In [58]:
df_2bw.loc[(df_2bw['Frequency[MHz]'] >= 1240) & (df_2bw['Frequency[MHz]'] <= 1250)]

,Sys,Band,Signal,Frequency[MHz],Bandwidth,Modulation,Rate(MHz),P_t (dBW),G_t (dBi),Alpha
9,GLO,L2,L2SF(P),1245.1,5.0,BPSK(5),5.1100,10.0,10.0,0.6
10,GLO,L2,L2OF(C/A),1245.1,0.5,BPSK(0.5),0.5110,10.0,10.0,0.6
12,GLO,L2,L2OC-D,1248.3,1.0,BPSK(1),1.0230,13.0,12.0,0.6
13,GLO,L2,L2OC-P,1248.3,2.0,"BOC(1,1)",0.5115,5.0,5.0,0.6

In [15]:
df_2bw.to_csv(path_or_buf='table3B_satellite_v3-1_reduced_2_bw.csv', index=None)

### ------------------------------ END -----------------------------------------